### ISSUE TITLE
MangoHud support

### ISSUE THREAD

**Issue by luni3359** [flathub/org.polymc.PolyMC#13]
I'm trying to run Minecraft with gamemode and mangohud but the sandbox isn't recognizing commands other than gamemode. I already enabled everything in Flatseal and it's still not recognizing them.

Sorry for the different language it just says that there's no such file or directory named mangohud. I also tried with prime-runx (my distro doesn't have prime-run so I made a bash alias named prime-runx)

![PolyMC log](https://user-images.githubusercontent.com/16832398/158052510-53563e8e-b2f8-4241-90a6-b416f29888da.png)

**Comment by dada513** [comment]
prime-run is available in the flatpak. Gamemode is manually added aswell. 
As far as I know, you only need to do something like this `flatpak override --user --env=MANGOHUD=1 org.polymc.PolyMC` to enable mangohud, but I will look into it

**Comment by luni3359** [comment]
I'm so dumb, I didn't realize that the prime-run script was already included, it works! But I couldn't get MangoHud to run at all. It seems like games running on OpenGL need `mangohud` to be run but with Vulkan `MANGOHUD=1` alone works. 

I have to run the official Minecraft Launcher like this for MangoHud to show up:
`MANGOHUD_DLSYM=1 mangohud minecraft-launcher`
as a whole my command looks like this:
`prime-run gamemoderun MANGOHUD_DLSYM=1 mangohud minecraft-launcher`

**Comment by dada513** [comment]
> I'm so dumb, I didn't realize that the prime-run script was already included, it works! But I couldn't get MangoHud to run at all. It seems like games running on OpenGL need `mangohud` to be run but with Vulkan `MANGOHUD=1` alone works. 
> 
> 
> 
> I have to run the official Minecraft Launcher like this for MangoHud to show up:
> 
> `MANGOHUD_DLSYM=1 mangohud minecraft-launcher`
> 
> as a whole my command looks like this:
> 
> `prime-run gamemoderun MANGOHUD_DLSYM=1 mangohud minecraft-launcher`

Let me see what I can do about that. Does official launcher via flatpak work?

**Comment by luni3359** [comment]
I'm using the .deb from here, it installs the official Minecraft launcher. I'm not sure if Microsoft is supporting the flatpak in flathub, but right now it seems like it's not very reliable.

I'll test tomorrow and let you know how it goes.

**Comment by dada513** [comment]
any results?

**Comment by TheEvilSkeleton** [comment]
I might be wrong, but you might get MangoHud working if you can add the [MangoHud flatpak](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud) as an extension. Similar to how you did with Gamescope:

https://github.com/flathub/org.polymc.PolyMC/blob/c6dd5f5675cd9e58c41a67e3f8f26147723e3e6f/org.polymc.PolyMC.yml#L9-L13

https://github.com/flathub/org.polymc.PolyMC/blob/c6dd5f5675cd9e58c41a67e3f8f26147723e3e6f/org.polymc.PolyMC.yml#L28

Afterwards, a build with this support is published, the user should be able to install the MangoHud flatpak by running `flatpak run org.freedesktop.Platform.VulkanLayer.MangoHud`, or by installing with GNOME Software (maybe Discover too?).

**Comment by sarahnya** [comment]
I had MangoHud working using `org.freedesktop.Platform.VulkanLayer.MangoHud` and the wrapper command `/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym` before but it didn't work today. I noticed the polymc flatpak is using the kde platform, was it using that before? I think maybe switching platform broke compatability?~

**Comment by sarahnya** [comment]
oh no wait I just checked on a different computer and mangohud is still working with the polymc flatpak on that computer~

**Comment by dada513** [comment]
it always used kde platform

**Comment by luni3359** [comment]
Sorry in the end I didn't go anywhere testing because I couldn't figure how to do it properly. Flatpak's sandboxing was already making several characters in Japanese unreadable due to a bug with flatpak itself so to spare me more problems I started using the AppImage and now everything works.

**Comment by jn64** [comment]
Hi, I have gamemode + MangoHud + PolyMC working.

1. PolyMC and MangoHud are installed via Flatpak.
   ```shell
   $ flatpak install org.polymc.PolyMC org.freedesktop.Platform.VulkanLayer.MangoHud
   ```

2. In PolyMC, set the wrapper command to `gamemoderun /usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym`

3. In order to use your existing (unsandboxed) MangoHud config in `~/.config/MangoHud`, do:
   ```shell
   $ flatpak override --user --filesystem=xdg-config/MangoHud:ro org.polymc.PolyMC
   ```

   Alternatively you can use Flatseal and add `xdg-config/MangoHud:ro` under the *Filesystem > Other files* section of PolyMC.

That's all! No need to set the `MANGOHUD` or `MANGOHUD_DLSYM` env vars.

Tested on Fedora 35.

**Comment by dada513** [comment]
@jn64 Thanks! I will add it to the readme

**Comment by cassiofb-dev** [comment]
Thanks for the tip @jn64 !

If you want to enable most of MangoHud variables by default you can set this variable on Flatseal:

![image](https://github.com/flathub/org.polymc.PolyMC/assets/61878987/33c209a8-1cbb-4fab-9f3c-b2ac2d1a60c2)

---

MangoHud in the game will appear like in the image bellow:

![image](https://github.com/flathub/org.polymc.PolyMC/assets/61878987/9a5e0bbd-eb62-4aee-9b04-0507dd2176f3)

---

Tested with:

![image](https://github.com/flathub/org.polymc.PolyMC/assets/61878987/d8900d21-2c4b-4d85-acfc-ceb196ff3b35)
