### ISSUE TITLE
Allow using Discord RPC

### ISSUE THREAD

**Issue by nchristopher** [flathub/org.polymc.PolyMC#14]
There's quite a few Minecraft mods that use Discord RPC, but Flatpaks require [some changes to the configuration](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)#flatpak-applications) to allow interfacing with Discord from inside the sandbox.

**Comment by dada513** [comment]
Already present

**Comment by dada513** [comment]
Fixed in 1.2.0
