### ISSUE TITLE
Drag and drop provides the wrong file path when importing from .zip.

### ISSUE THREAD

**Issue by Regular-Baf** [flathub/org.polymc.PolyMC#15]
I'm running Fedora 35 with plasma wayland, pretty much everything is stock.

### File path provided with a drag and drop
![image](https://user-images.githubusercontent.com/95348524/159415586-37094d66-9d33-478b-ac00-6b47a93498a2.png)
_As you can see, the okay button is greyed out._

### File path provided when importing the zip through the file explorer portal thingy
![image](https://user-images.githubusercontent.com/95348524/159414865-f0dec8a9-1c77-44cb-b8a3-08b5c3c304a0.png)
_Like this it works just fine._

This may also be the reason that drag and drop with mods, resource packs and shaders don't work. I'm not sure though.

**Comment by dada513** [comment]
This is tough, portals dont really like Qt drag and drop.
For now i've given Downloads permission to at least somewhat combat the issue.
I'm trying to at least improve the error handling with sandbox issues in https://github.com/PolyMC/PolyMC/pull/355

**Comment by dada513** [comment]
This is something qt needs to do ):
