### ISSUE TITLE
journalctl being spammed with QCorApplication::postEvent: Unexpected null receiver

### ISSUE THREAD

**Issue by Schmensch** [flathub/org.polymc.PolyMC#17]
OS: Fedora 36

PolyMC decided to completely spam my journalctl with `QCoreApplication::postEvent: Unexpected null receiver`, more than a thousand times a second.

**Comment by dada513** [comment]
Can't reproduce, does the same happen with the COPR version?

**Comment by Schmensch** [comment]
Don't know what happened either, I also can't repoduce it and it didn't happen since.

Closing this.
