### ISSUE TITLE
Unable to Open Links

### ISSUE THREAD

**Issue by Merith-TK** [flathub/org.polymc.PolyMC#27]
Basically, PolyMC flatpak doesnt have the permission required to open links in browsers, but I dont know the flatpak permission it needs to grant this ability

**Comment by dada513** [comment]
Works on my machine. Are you on steam deck?

**Comment by Merith-TK** [comment]
Steam deck in desktop and game mode

**Comment by dada513** [comment]
> Steam deck in desktop and game mode

Steam deck issue, it doesn't work on mine either, they didn't setup flatpak properly there's nothing I can do. It works on normal Linux machines

**Comment by Merith-TK** [comment]
can you check the permissions of the flatpak? see what it has access to in flatseal and share?

flatseal is the go to for modifying flatpak perms on the deck at the moment

**Comment by binex-dsk** [comment]
in other words: skill issue
