### ISSUE TITLE
Is permission device=all necessary?

### ISSUE THREAD

**Issue by Theta-Dev** [flathub/org.polymc.PolyMC#29]
I have just installed PolyMC on my new system and looked through the flatpak permissions. I noticed that PolyMC has the ``device=all`` permission, which grants the application access to all devices, including cameras, which can be a privacy risk.

So I disabled access to all devices with this command (``device=dri`` is necessary for OpenGL) and everything works just fine.
```
sudo flatpak override --nodevice=all --device=dri org.polymc.PolyMC
```

Is that permission necessary for features that I'm not aware of (gamepad access, maybe?)
If that is the case, I would suggest adding a comment to explain it.

**Comment by dada513** [comment]
I think gamepad access and microphones (for mods such as plasmo voice). I don't have any notes about why I did this, so I don't remember fully though

**Comment by Theta-Dev** [comment]
Alright. Then I'll simply override it for my personal use. Thanks for the info.
