### ISSUE TITLE
Flatpak is oversized

### ISSUE THREAD

**Issue by SViN24** [flathub/org.polymc.PolyMC#7]
![image](https://user-images.githubusercontent.com/51864332/151656056-5ba54aa5-6984-402d-b26a-67c098262cf7.png)

for some reason it seems the polyMC flatpak on its own is 300 MB

**Comment by dada513** [comment]
Because it needs to download Java it's larger but I'm not sure it should weigh that much I'll double check if there isn't useless things in it

**Comment by dada513** [comment]
It's probably the custom wayland GLFW that doesn't work well anyway so I'll just get rid of it for now and maybe package it later as an add on

**Comment by dada513** [comment]
I have removed GLFW and cleaned up things. Waiting for build so I can see if its still bad

**Comment by dada513** [comment]
I got it down to 230.
This is probably minimum cause java

**Comment by dada513** [comment]
I got it down to 230.
This is probably minimum cause java

**Comment by SViN24** [comment]
considering the yml file is pulling the flathub openjdk extension wouldn't it be possible to just use that?

**Comment by dada513** [comment]
> considering the yml file is pulling the flathub openjdk extension wouldn't it be possible to just use that?

it is using that. For some reason it doesn't show that it's downloading it but it is definietly used.
