### ISSUE TITLE
Runtime version should probably be 5.15-21.08, to allow use of extensions to the freedesktop platform

### ISSUE THREAD

**Issue by ljmc2000** [flathub/org.polymc.PolyMC#8]
At present, plugins such as org.freedesktop.Platform.VulkanLayer.OBSVkCapture and org.freedesktop.Platform.VulkanLayer.MangoHud can not be used with this launcher under flatpak (both work outside of flatpak). But they would 100% work if the runtime version was 5.15-21.08 like in the title. I know very little about flatpak, so I'm not sure how trivial or complex such a change would be, but I thought I'd bring this to your attention.

https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture/issues/2

**Comment by dada513** [comment]
Thanks for the report, I will work on this today

**Comment by dada513** [comment]
Ok, so kde by default uses 20.08, but it should be updated I agree. 
Download will take a while, hopefully I can push the updates today

**Comment by dada513** [comment]
Pushed an update to both `beta` and `master`. Should be built by flathub in a few hours, please test if everything works fine after the update is available.

**Comment by ljmc2000** [comment]
Just pulled update from flathub. Able to use obs-glcapture without previously nessesary workaround of overriding the runtime. However, it's not included in the $PATH variable, so just typing obs-glcapture in the wrapper command box doesn't work. It has to be /usr/lib/extensions/vulkan/OBSVkCapture/bin/obs-glcapture for some reason.

Thanks, that's one issue fixed anyway.
